name: dsa_flashcards_app
description: A DSA Flashcard Learning App with Leitner system, animations, and Firebase sync
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.68.0
  flip_card: ^0.7.0
  flutter_slidable: ^3.1.0
  flutter_local_notifications: ^15.0.0
  timezone: ^0.9.0
  audioplayers: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/correct.mp3
    - assets/sounds/wrong.mp3
# pubspec.yaml content (use the full pubspec.yaml provided earlier)